// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz931F7ThtYxXr_KqvcgmqUXLDq4qSbXc',
    appId: '1:108205942195:web:f228c75a6e123ba52197c6',
    messagingSenderId: '108205942195',
    projectId: 'shipday-drive',
    authDomain: 'shipday-drive.firebaseapp.com',
    databaseURL: 'https://shipday-drive-default-rtdb.firebaseio.com',
    storageBucket: 'shipday-drive.appspot.com',
    measurementId: 'G-8JW3EMTP2H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxWjumKKrk8y4AcmqAM0mURqZtkVWDXYk',
    appId: '1:108205942195:android:a3d686d62f3267eb2197c6',
    messagingSenderId: '108205942195',
    projectId: 'shipday-drive',
    databaseURL: 'https://shipday-drive-default-rtdb.firebaseio.com',
    storageBucket: 'shipday-drive.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjfM8gRPK0RjL4URq4tfxUUnN8TlMbH1A',
    appId: '1:108205942195:ios:a0467d9a746b0e9f2197c6',
    messagingSenderId: '108205942195',
    projectId: 'shipday-drive',
    databaseURL: 'https://shipday-drive-default-rtdb.firebaseio.com',
    storageBucket: 'shipday-drive.appspot.com',
    iosClientId: '108205942195-vic0ng2c98pm8eqgva7luo8tp0lggs61.apps.googleusercontent.com',
    iosBundleId: 'com.example.tr1',
  );
}
